// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluwrhnhyasfomydvvja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdXdyaG5oeWFzZm9teWR2dmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjcxNzIsImV4cCI6MjA3MTg0MzE3Mn0.OpPnMuofIkUh2wvIJbn9uRPSFkxJhfgui-9DIoVfcio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});